# Generated by Django 2.2.1 on 2019-05-11 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(default='')),
                ('senha', models.TextField(default='')),
                ('matricula', models.TextField(default='')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('cpf', models.IntegerField(null=True)),
                ('curso', models.TextField(default='')),
                ('data_nascimento', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.TextField(default='')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('qualis', models.TextField(default='')),
                ('area', models.TextField(default='')),
                ('local', models.TextField(default='')),
                ('descricao', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('cpf', models.IntegerField(null=True, unique=True)),
                ('email', models.TextField()),
                ('data_nascimento', models.TextField(max_length=20)),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(default='')),
                ('senha', models.TextField(default='')),
                ('matricula', models.TextField()),
                ('cpf', models.IntegerField(null=True)),
                ('curso', models.TextField(default='')),
                ('email', models.TextField()),
                ('data_nascimento', models.TextField(max_length=20)),
                ('funcao', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='StatusArtigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, null=True)),
                ('titulo', models.TextField()),
                ('corpo', models.TextField()),
                ('data_lancamento_noticia', models.DateTimeField(null=True)),
                ('imagem', models.ImageField(upload_to='noticias')),
                ('autor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(default='')),
                ('coautor', models.TextField(default='')),
                ('orientador', models.TextField(default='')),
                ('autor', models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Pessoa')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.StatusArtigo')),
            ],
        ),
    ]
