# Generated by Django 2.2.1 on 2019-05-12 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0006_auto_20190512_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='horarios_laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField(default='')),
                ('hora_saida', models.DateTimeField(default='')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Aluno')),
            ],
        ),
    ]
