# Generated by Django 2.2.1 on 2019-05-13 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0009_auto_20190513_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='user',
        ),
    ]
