# Generated by Django 2.2.1 on 2019-05-29 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0012_aluno_usuario_u'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='usuario_u',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
